In [15]:
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
data_dir = './data'

In [17]:
data_casy = pd.read_csv(f'{data_dir}/Casy.csv', index_col=False)
data_casy.head()

,sample_type,channel,replicate,mean_diameter,peak_diameter,sample_dilution,measurement_name,sample_volume,casyton_volume,measurement_volume,counts
0,ABB,4,1,2.0477,1.519,2,13,10,10000,200,2212
1,ABB,4,2,2.0490,1.460,2,13,10,10000,200,2292
2,ABB,4,3,2.0726,1.616,2,13,10,10000,200,2407
3,ABB,5,1,2.1146,1.479,2,6,10,10000,200,570
4,ABB,5,2,2.0694,1.577,2,6,10,10000,200,625

In [18]:
data_design = pd.read_csv(f'{data_dir}/Design.csv', index_col=False)
data_design.head()

   channel    purpose  phosphate_mM
0        1  treatment        0.0115
1        3  treatment        0.0115
2        4  treatment        0.0115
3        5    control        0.2300
4        7    control        0.2300

In [19]:
data_qpcr = pd.read_csv(f'{data_dir}/Qpcr.csv', index_col=False)
data_qpcr.head()

,sample_id,channel,replicate,dilution_replicate,Ct,dilution_factor,sample_class,template_vol,final_vol
0,200206_0_4,4.0,1,1.0,15,10,sample,5,20
1,200206_2_7,5.0,1,1.0,13,10,sample,5,20
2,200206_2_5,7.0,1,1.0,13,10,sample,5,20
3,200207_2_6,8.0,1,1.0,13,10,sample,5,20
4,200207_2_3,3.0,1,1.0,15,10,sample,5,20

In [20]:
data_spectra = pd.read_csv(f'{data_dir}/Spectrophotometer.csv', index_col=False)
data_spectra.head()

   od_value_730  od_value_685  od_value_634  od_value_720  channel
0         0.207         0.295         0.314         0.219        7
1         0.155         0.197         0.231         0.161        4
2         0.180         0.221         0.252         0.186        1
3         0.259         0.351         0.370         0.271        8
4         0.183         0.219         0.252         0.189        3

In [21]:
data_turbidity = pd.read_csv(f'{data_dir}/Turbidostat.csv', index_col=False)
data_turbidity.head()

   channel  decision    time_h      OD
0        1       145  297.2658  0.3343
1        1       145  297.3492  0.3338
2        1       145  297.4325  0.3318
3        1       145  297.5158  0.3338
4        1       145  297.5992  0.3318