In [33]:
import pandas as pd
import matplotlib.pyplot as plt

In [34]:
data_dir = './data'

In [35]:
data_casy = pd.read_csv(f'{data_dir}/Casy.csv', index_col=False)
data_casy.head(20)

,sample_type,channel,replicate,mean_diameter,peak_diameter,sample_dilution,measurement_name,sample_volume,casyton_volume,measurement_volume,counts
0,ABB,4,1,2.0477,1.519,2,13,10,10000,200,2212
1,ABB,4,2,2.0490,1.460,2,13,10,10000,200,2292
2,ABB,4,3,2.0726,1.616,2,13,10,10000,200,2407
3,ABB,5,1,2.1146,1.479,2,6,10,10000,200,570
4,ABB,5,2,2.0694,1.577,2,6,10,10000,200,625
5,ABB,5,3,2.1109,1.421,2,6,10,10000,200,689
6,ABB,7,1,1.9748,1.538,2,4,10,10000,200,788
7,ABB,7,2,1.9697,1.538,2,4,10,10000,200,796
8,ABB,7,3,1.9650,1.606,2,4,10,10000,200,818
9,BBB,4,1,2.1149,1.802,50,12,10,10000,200,1521
10,BBB,4,2,2.1186,1.743,50,12,10,10000,200,1501
11,BBB,4,3,2.1046,1.890,50,12,10,10000,200,1489
12,BBB,5,1,1.8801,1.714,50,5,10,10000,200,2067
13,BBB,5,2,1.8858,1.626,50,5,10,10000,200,1864
14,BBB,5,3,1.8629,1.665,50,5,10,10000,200,1980
15,BBB,7,1,1.8475,1.694,50,3,10,10000,200,1550
16,BBB,7,2,1.8335,1.616,50,3,10,10000,200,1591
17,BBB,7,3,1.8504,1.626,50,3,10,10000,200,1596
18,MC,4,1,2.0732,1.782,1,11,10,10000,200,4644
19,MC,4,2,2.0593,1.753,1,11,10,10000,200,4581

In [36]:
# qPCR cycle threshold (Ct) values are inversely proportional to the amount of target nucleic acid in the sample. 
# A lower Ct value indicates a higher amount of target nucleic acid, 
# while a higher Ct value indicates a lower amount of target nucleic acid. 
# This is because it takes fewer cycles for the fluorescence signal to reach 
# the threshold when there is more target nucleic acid present in the sample.

data_qpcr = pd.read_csv(f'{data_dir}/qPCR.csv', index_col=False)
data_qpcr.head(100)

# order by sample and time
data_qpcr = data_qpcr.sort_values(by=['sample_id'])
data_qpcr.head(100)

#Ct change per sample

,sample_id,channel,replicate,dilution_replicate,Ct,dilution_factor,sample_class,template_vol,final_vol
0,200206_0_4,4.0,1,1.0,15,10,sample,5,20
18,200206_0_4,4.0,2,1.0,15,10,sample,5,20
30,200206_0_4,4.0,2,3.0,21,1000,sample,5,20
6,200206_0_4,4.0,1,2.0,18,100,sample,5,20
12,200206_0_4,4.0,1,3.0,21,1000,sample,5,20
24,200206_0_4,4.0,2,2.0,18,100,sample,5,20
26,200206_2_5,7.0,2,2.0,16,100,sample,5,20
20,200206_2_5,7.0,2,1.0,13,10,sample,5,20
2,200206_2_5,7.0,1,1.0,13,10,sample,5,20
14,200206_2_5,7.0,1,3.0,19,1000,sample,5,20
8,200206_2_5,7.0,1,2.0,17,100,sample,5,20
32,200206_2_5,7.0,2,3.0,19,1000,sample,5,20
31,200206_2_7,5.0,2,3.0,20,1000,sample,5,20
13,200206_2_7,5.0,1,3.0,20,1000,sample,5,20
1,200206_2_7,5.0,1,1.0,13,10,sample,5,20
19,200206_2_7,5.0,2,1.0,12,10,sample,5,20
7,200206_2_7,5.0,1,2.0,18,100,sample,5,20
25,200206_2_7,5.0,2,2.0,16,100,sample,5,20
11,200207_0_8,1.0,1,2.0,19,100,sample,5,20
23,200207_0_8,1.0,2,1.0,15,10,sample,5,20
29,200207_0_8,1.0,2,2.0,17,100,sample,5,20
17,200207_0_8,1.0,1,3.0,22,1000,sample,5,20
35,200207_0_8,1.0,2,3.0,21,1000,sample,5,20
5,200207_0_8,1.0,1,1.0,15,10,sample,5,20
34,200207_2_3,3.0,2,3.0,22,1000,sample,5,20
28,200207_2_3,3.0,2,2.0,18,100,sample,5,20
16,200207_2_3,3.0,1,3.0,22,1000,sample,5,20
10,200207_2_3,3.0,1,2.0,18,100,sample,5,20
4,200207_2_3,3.0,1,1.0,15,10,sample,5,20
22,200207_2_3,3.0,2,1.0,15,10,sample,5,20
21,200207_2_6,8.0,2,1.0,12,10,sample,5,20
27,200207_2_6,8.0,2,2.0,16,100,sample,5,20
15,200207_2_6,8.0,1,3.0,19,1000,sample,5,20
9,200207_2_6,8.0,1,2.0,16,100,sample,5,20
33,200207_2_6,8.0,2,3.0,19,1000,sample,5,20
3,200207_2_6,8.0,1,1.0,13,10,sample,5,20
43,S1,NaN,2,NaN,9,10,standard,5,20
50,S1,NaN,3,NaN,9,10,standard,5,20
36,S1,NaN,1,NaN,9,10,standard,5,20
51,S2,NaN,3,NaN,12,100,standard,5,20
44,S2,NaN,2,NaN,12,100,standard,5,20
37,S2,NaN,1,NaN,12,100,standard,5,20
45,S3,NaN,2,NaN,15,1000,standard,5,20
52,S3,NaN,3,NaN,15,1000,standard,5,20
38,S3,NaN,1,NaN,15,1000,standard,5,20
39,S4,NaN,1,NaN,18,10000,standard,5,20
53,S4,NaN,3,NaN,18,10000,standard,5,20
46,S4,NaN,2,NaN,19,10000,standard,5,20
40,S5,NaN,1,NaN,22,100000,standard,5,20
54,S5,NaN,3,NaN,21,100000,standard,5,20
47,S5,NaN,2,NaN,22,100000,standard,5,20
41,S6,NaN,1,NaN,25,1000000,standard,5,20
48,S6,NaN,2,NaN,25,1000000,standard,5,20
55,S6,NaN,3,NaN,24,1000000,standard,5,20
42,S7,NaN,1,NaN,29,10000000,standard,5,20
49,S7,NaN,2,NaN,28,10000000,standard,5,20
56,S7,NaN,3,NaN,27,10000000,standard,5,20

In [37]:
### Casy Counter
# Protocol
# 1. Dilute sample of interest (measurement range)
# 2. Pipette 10 μL dilution into CASY-vial with 10 mL of CASY-ton buffer
# 3. Insert CASY-vial into CASY-counter
# 4. Measure:
#     - CASY-counter will perform 3 measurements of each sample
#     - Each measurement will take 200 μL from CASY-vial
#     - The machine will report for each measurement:
#         - Total number of counts
#         - Peak diameter
#         - Average diameter

In [38]:
# cells per ml = counts * dilution factor
# The dilution factor is calculated as the total volume after dilution divided by the volume of the sample. 
# In this case, the total volume after dilution is 10010 ml and the volume of the sample is 10 ml, so the dilution factor is 10010 / 10 = 1001.

dilution_factor = 1001 # 10010 / 10
data_casy['cells_per_ml'] = data_casy['counts'] * dilution_factor
data_casy.head(10)

,sample_type,channel,replicate,mean_diameter,peak_diameter,sample_dilution,measurement_name,sample_volume,casyton_volume,measurement_volume,counts,cells_per_ml
0,ABB,4,1,2.0477,1.519,2,13,10,10000,200,2212,2214212
1,ABB,4,2,2.0490,1.460,2,13,10,10000,200,2292,2294292
2,ABB,4,3,2.0726,1.616,2,13,10,10000,200,2407,2409407
3,ABB,5,1,2.1146,1.479,2,6,10,10000,200,570,570570
4,ABB,5,2,2.0694,1.577,2,6,10,10000,200,625,625625
5,ABB,5,3,2.1109,1.421,2,6,10,10000,200,689,689689
6,ABB,7,1,1.9748,1.538,2,4,10,10000,200,788,788788
7,ABB,7,2,1.9697,1.538,2,4,10,10000,200,796,796796
8,ABB,7,3,1.9650,1.606,2,4,10,10000,200,818,818818
9,BBB,4,1,2.1149,1.802,50,12,10,10000,200,1521,1522521